/api/v1/roles/list:
  get:
    tags:
      - Role
    security:
      - bearerAuth: []
    summary: Obtiene una lista de roles.
    description: Obtiene una lista de todos los roles existentes en la base de datos.
    responses:
      200:
        description: OK.
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: boolean
                  example: true
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id_role:
                        type: integer
                        example: 1
                      role_name:
                        type: string
                        example: "Admin"
                      created_at:
                        type: string
                        format: date-time
                        example: "2022-03-22T12:47:21.017Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2022-03-22T12:47:21.017Z"
      400:
        description: Bad Request.
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: "Error obteniendo roles."